// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaADo3YLhxFhXYlPdXmHnU5qbL1ZKU91c',
    appId: '1:666709690528:web:fc2d4bcff96189149c21c5',
    messagingSenderId: '666709690528',
    projectId: 'apploansag',
    authDomain: 'apploansag.firebaseapp.com',
    storageBucket: 'apploansag.firebasestorage.app',
    measurementId: 'G-TKSGPSTX7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxomDVjCoAIoVjNsvvETjGBa5gNx0AlaI',
    appId: '1:666709690528:android:e8b934f2957b922e9c21c5',
    messagingSenderId: '666709690528',
    projectId: 'apploansag',
    storageBucket: 'apploansag.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALJgw3IK-DXz03Lxm4JoHSQnnLd5vWUhM',
    appId: '1:666709690528:ios:65b28d171e24420e9c21c5',
    messagingSenderId: '666709690528',
    projectId: 'apploansag',
    storageBucket: 'apploansag.firebasestorage.app',
    iosBundleId: 'com.example.appLoansAg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALJgw3IK-DXz03Lxm4JoHSQnnLd5vWUhM',
    appId: '1:666709690528:ios:65b28d171e24420e9c21c5',
    messagingSenderId: '666709690528',
    projectId: 'apploansag',
    storageBucket: 'apploansag.firebasestorage.app',
    iosBundleId: 'com.example.appLoansAg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaADo3YLhxFhXYlPdXmHnU5qbL1ZKU91c',
    appId: '1:666709690528:web:aa3a63967d70f12b9c21c5',
    messagingSenderId: '666709690528',
    projectId: 'apploansag',
    authDomain: 'apploansag.firebaseapp.com',
    storageBucket: 'apploansag.firebasestorage.app',
    measurementId: 'G-ZL68N1VEY3',
  );

}